import { Inter } from "next/font/google";
import "./globals.css";
import LayoutProvider from "@/components/LayoutProvider/LayoutProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Students save",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-gray-950 text-gray-300"}>
        <div className="__next">
          <LayoutProvider>
            {children}
          </LayoutProvider>
        </div>
      </body>
    </html>
  );
}
